# Copyright (c) 2023 Matthias Mair<code@mjmair.com>
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-docstrings",
            "flake8-string-format",
            "pep8-naming ",
          ]
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/johannsdg/pre-commit-license-headers
    rev: d53087d331942f263cb553dc67b0e51ffa3a3481 # Use the ref you want to point at
    hooks:
      - id: check-license-headers
        args:
          - "--template"
          - Copyright (c) [YEARS] [OWNER]
          - "--owner=Matthias Mair<code@mjmair.com>"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
              docs/docs/stylesheets/.*|
              docs/docs/javascripts/.*|
              docs/docs/webfonts/.*
          )$
