exclude: .*/(static|migrations|locale)/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
  - repo: https://github.com/johannsdg/pre-commit-license-headers
    rev: d53087d331942f263cb553dc67b0e51ffa3a3481 # Use the ref you want to point at
    hooks:
    - id: check-license-headers
      args:
      - "--template"
      - Copyright (c) [YEARS] [OWNER]
      - "--owner=Matthias Mair<code@mjmair.com>"
